apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s.web.com/name: db
  name: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph
  volumeMode: Filesystem
