apiVersion: v1
kind: Service
metadata:
  labels:
    k8s.web.com/name: web
  name: web
spec:
  selector:
    k8s.web.com/name: web
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  type: ClusterIP